// Mocks generated by Mockito 5.4.6 from annotations
// in bravoball_flutter/test/unit/services/store_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:bravoball_flutter/services/api_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiResponse_0<T> extends _i1.SmartFake
    implements _i2.ApiResponse<T> {
  _FakeApiResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i2.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void initialize() => super.noSuchMethod(
    Invocation.method(#initialize, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<_i2.ApiResponse<Map<String, dynamic>>> request({
    required String? endpoint,
    String? method = 'GET',
    Map<String, String>? headers,
    Map<String, dynamic>? body,
    Map<String, String>? queryParameters,
    bool? requiresAuth = false,
    bool? isRetry = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#request, [], {
              #endpoint: endpoint,
              #method: method,
              #headers: headers,
              #body: body,
              #queryParameters: queryParameters,
              #requiresAuth: requiresAuth,
              #isRetry: isRetry,
            }),
            returnValue:
                _i3.Future<_i2.ApiResponse<Map<String, dynamic>>>.value(
                  _FakeApiResponse_0<Map<String, dynamic>>(
                    this,
                    Invocation.method(#request, [], {
                      #endpoint: endpoint,
                      #method: method,
                      #headers: headers,
                      #body: body,
                      #queryParameters: queryParameters,
                      #requiresAuth: requiresAuth,
                      #isRetry: isRetry,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i2.ApiResponse<Map<String, dynamic>>>);

  @override
  _i3.Future<_i2.ApiResponse<Map<String, dynamic>>> get(
    String? endpoint, {
    Map<String, String>? queryParameters,
    Map<String, String>? headers,
    bool? requiresAuth = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [endpoint],
              {
                #queryParameters: queryParameters,
                #headers: headers,
                #requiresAuth: requiresAuth,
              },
            ),
            returnValue:
                _i3.Future<_i2.ApiResponse<Map<String, dynamic>>>.value(
                  _FakeApiResponse_0<Map<String, dynamic>>(
                    this,
                    Invocation.method(
                      #get,
                      [endpoint],
                      {
                        #queryParameters: queryParameters,
                        #headers: headers,
                        #requiresAuth: requiresAuth,
                      },
                    ),
                  ),
                ),
          )
          as _i3.Future<_i2.ApiResponse<Map<String, dynamic>>>);

  @override
  _i3.Future<_i2.ApiResponse<Map<String, dynamic>>> post(
    String? endpoint, {
    Map<String, dynamic>? body,
    Map<String, String>? headers,
    bool? requiresAuth = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [endpoint],
              {#body: body, #headers: headers, #requiresAuth: requiresAuth},
            ),
            returnValue:
                _i3.Future<_i2.ApiResponse<Map<String, dynamic>>>.value(
                  _FakeApiResponse_0<Map<String, dynamic>>(
                    this,
                    Invocation.method(
                      #post,
                      [endpoint],
                      {
                        #body: body,
                        #headers: headers,
                        #requiresAuth: requiresAuth,
                      },
                    ),
                  ),
                ),
          )
          as _i3.Future<_i2.ApiResponse<Map<String, dynamic>>>);

  @override
  _i3.Future<_i2.ApiResponse<Map<String, dynamic>>> put(
    String? endpoint, {
    Map<String, dynamic>? body,
    Map<String, String>? headers,
    bool? requiresAuth = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [endpoint],
              {#body: body, #headers: headers, #requiresAuth: requiresAuth},
            ),
            returnValue:
                _i3.Future<_i2.ApiResponse<Map<String, dynamic>>>.value(
                  _FakeApiResponse_0<Map<String, dynamic>>(
                    this,
                    Invocation.method(
                      #put,
                      [endpoint],
                      {
                        #body: body,
                        #headers: headers,
                        #requiresAuth: requiresAuth,
                      },
                    ),
                  ),
                ),
          )
          as _i3.Future<_i2.ApiResponse<Map<String, dynamic>>>);

  @override
  _i3.Future<_i2.ApiResponse<Map<String, dynamic>>> patch(
    String? endpoint, {
    Map<String, dynamic>? body,
    Map<String, String>? headers,
    bool? requiresAuth = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [endpoint],
              {#body: body, #headers: headers, #requiresAuth: requiresAuth},
            ),
            returnValue:
                _i3.Future<_i2.ApiResponse<Map<String, dynamic>>>.value(
                  _FakeApiResponse_0<Map<String, dynamic>>(
                    this,
                    Invocation.method(
                      #patch,
                      [endpoint],
                      {
                        #body: body,
                        #headers: headers,
                        #requiresAuth: requiresAuth,
                      },
                    ),
                  ),
                ),
          )
          as _i3.Future<_i2.ApiResponse<Map<String, dynamic>>>);

  @override
  _i3.Future<_i2.ApiResponse<Map<String, dynamic>>> delete(
    String? endpoint, {
    Map<String, String>? headers,
    bool? requiresAuth = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [endpoint],
              {#headers: headers, #requiresAuth: requiresAuth},
            ),
            returnValue:
                _i3.Future<_i2.ApiResponse<Map<String, dynamic>>>.value(
                  _FakeApiResponse_0<Map<String, dynamic>>(
                    this,
                    Invocation.method(
                      #delete,
                      [endpoint],
                      {#headers: headers, #requiresAuth: requiresAuth},
                    ),
                  ),
                ),
          )
          as _i3.Future<_i2.ApiResponse<Map<String, dynamic>>>);
}
